apiVersion: apps/v1
kind: Deployment
metadata:
    name: aditya-nagp-assignment-web-deploy
    labels:
        app: web
spec:
    replicas: {{.Values.replicas}}
    selector: 
        matchLabels: 
            app: web
    template: 
        metadata:
            labels:
                app: web
        spec:
            terminationGracePeriodSeconds: 1
            containers:
                - name: aditya-nagp-assignment-pod-container
                  image: {{.Values.image}}
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 8080
                
---

apiVersion: v1
kind: Service
metadata:
    name: aditya-nagp-assignment-service
spec:
    type: NodePort
    ports: 
    - port: 80
      targetPort: 8080
      nodePort: {{ .Values.nodeport }}
      protocol: TCP
    selector: 
        app: web